<?php
namespace Allty;

require dirname(__DIR__).'/../../lib/Allty/JSONCom.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 14:19:52.
 */
class JSONComTest extends \PHPUnit_Framework_TestCase {
    
    /**
     * @covers Allty\JSONCom::decode
     */
    public function testDecode()
    {
        $json = array(
            // Double slash comment
            '// Comment
            { "foo" : "bar" }
            // other comment',
            
            // # comment
            '# Comment
            { "foo" : "bar" }
            # other comment',
            
            // multi-line comment
            '/* Comment
                on multiple lines */
            { "foo" : "bar" }
            /* other comment */'
        );

        $expected = new \stdClass();
        $expected->foo = 'bar';
        
        foreach($json as $str) {
            $decoded = JSONCom::decode($str);    
            $this->assertEquals($expected, $decoded, 'Expected parsing failed.');
        }
    }
}
